# このconfigは、 dockerでMisskey本体を起動せず、 redisとpostgresql などだけを起動します

services:
  redis:
    restart: always
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.3.4
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#    env_file:
#      - .config/meilisearch.env
#    volumes:
#      - ./meili_data:/meili_data

# opensearchとopensearch-dashboardsのdockerfileは実装時の最新版の辞書なのでopensearch/dockerfileを適宜書き換えてください
# opensearchはUID:1000で実行されるので読み書きできるよう所有者を書き換える chown 1000:1000 ./data/opensearch
#  opensearch:
#    build: ./opensearch
#    environment:
#      - "server.ssl.enabled:false"
#      - "discovery.type=single-node"
#      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=opensearch-adminpassword" #強めのパスワードじゃないと怒られる
#      - "plugins.security.disabled=true"
#    ulimits:
#      memlock:
#        soft: -1 # Set memlock to unlimited (no soft or hard limit)
#        hard: -1
#      nofile:
#        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
#        hard: 65536
#    volumes:
#      - ./os-data:/usr/share/opensearch/data
#    networks:
#      - internal_network
#      - external_network

#OpenSearchのダッシュボードを見る場合に必要
#  opensearch-dashboards:
#    build: ./opensearch-dashboards
#    ports:
#      - 5601:5601
#    links:
#      - opensearch
#    expose:
#      - '5601'
#    environment:
#      OPENSEARCH_HOSTS: 'http://opensearch:9200'
#    networks:
#      - internal_network
#      - external_network
