services:
  setup:
    volumes:
      - type: volume
        source: node_modules
        target: /cherrypick/node_modules
      - type: volume
        source: node_modules_backend
        target: /cherrypick/packages/backend/node_modules
      - type: volume
        source: node_modules_cherrypick-js
        target: /cherrypick/packages/cherrypick-js/node_modules
      - type: volume
        source: node_modules_misskey-reversi
        target: /cherrypick/packages/misskey-reversi/node_modules

  tester:
    networks:
      external_network:
      internal_network:
        ipv4_address: 172.20.1.1
    volumes:
      - type: volume
        source: node_modules_dev
        target: /cherrypick/node_modules
      - type: volume
        source: node_modules_backend_dev
        target: /cherrypick/packages/backend/node_modules
      - type: volume
        source: node_modules_cherrypick-js_dev
        target: /cherrypick/packages/cherrypick-js/node_modules

  daemon:
    networks:
      - external_network
      - internal_network_a
      - internal_network_b
    volumes:
      - type: volume
        source: node_modules_dev
        target: /cherrypick/node_modules
      - type: volume
        source: node_modules_backend_dev
        target: /cherrypick/packages/backend/node_modules

  redis.test:
    networks:
      - internal_network_a
      - internal_network_b

  a.test:
    networks:
      - internal_network

  cherrypick.a.test:
    networks:
      - external_network
      - internal_network
    volumes:
      - type: volume
        source: node_modules
        target: /cherrypick/node_modules
      - type: volume
        source: node_modules_backend
        target: /cherrypick/packages/backend/node_modules
      - type: volume
        source: node_modules_cherrypick-js
        target: /cherrypick/packages/cherrypick-js/node_modules
      - type: volume
        source: node_modules_misskey-reversi
        target: /cherrypick/packages/misskey-reversi/node_modules

  b.test:
    networks:
      - internal_network

  cherrypick.b.test:
    networks:
      - external_network
      - internal_network
    volumes:
      - type: volume
        source: node_modules
        target: /cherrypick/node_modules
      - type: volume
        source: node_modules_backend
        target: /cherrypick/packages/backend/node_modules
      - type: volume
        source: node_modules_cherrypick-js
        target: /cherrypick/packages/cherrypick-js/node_modules
      - type: volume
        source: node_modules_misskey-reversi
        target: /cherrypick/packages/misskey-reversi/node_modules

networks:
  external_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          ip_range: 172.23.0.0/24
  internal_network:
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/24

volumes:
  node_modules:
  node_modules_dev:
  node_modules_backend:
  node_modules_backend_dev:
  node_modules_cherrypick-js:
  node_modules_cherrypick-js_dev:
  node_modules_misskey-reversi:
