url: 'http://cherrypick.local'

# ローカルでテストするときにポートを被らないようにするためデフォルトのものとは変える(以下同じ)
port: 61812

db:
  host: 127.0.0.1
  port: 54312
  db: test-cherrypick
  user: postgres
  pass: ''
redis:
  host: 127.0.0.1
  port: 56312
id: aidx

fulltextSearch:
  provider: opensearch

opensearch:
  host: 127.0.0.1
  port: 59200
  user: 'admin'
  pass: 'eF53xwF4NYjrcXXwZ2CHgpwFL'
  ssl: false
  index: 'instancename' #なんでもいい
