name: Lint

on:
  push:
    branches:
      - master
      - develop
    paths:
      - packages/backend/**
      - packages/frontend/**
      - packages/sw/**
      - packages/cherrypick-js/**
      - packages/shared/.eslintrc.js
  pull_request:
    paths:
      - packages/backend/**
      - packages/frontend/**
      - packages/sw/**
      - packages/cherrypick-js/**
      - packages/shared/.eslintrc.js

jobs:
  pnpm_install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        submodules: true
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4.0.2
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile

  lint:
    needs: [pnpm_install]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        workspace:
        - backend
        - frontend
        - sw
        - cherrypick-js
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        submodules: true
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4.0.2
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - run: pnpm --filter ${{ matrix.workspace }} run eslint

  typecheck:
    needs: [pnpm_install]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        workspace:
        - backend
        - cherrypick-js
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        submodules: true
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4.0.2
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - run: pnpm --filter cherrypick-js run build
      if: ${{ matrix.workspace == 'backend' }}
    - run: pnpm --filter misskey-reversi run build
      if: ${{ matrix.workspace == 'backend' }}
    - run: pnpm --filter ${{ matrix.workspace }} run typecheck
